swagger: '2.0'
info:
  title: 'Dentist API'
  version: '1.0.0'
  description: 'API for listing dentists and retrieving each dentist'
schemes:
  - http
  - https
host: 'localhost:5001'
basePath: '/v1'
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
paths:
  /dentists:
    get:
      produces:
        - application/json
      parameters:
        - name: name
          description: Name of the dentist
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Successfully listed dentists
          schema:
            items:
              $ref: '#/definitions/Dentist'
            type: array
        '405':
          description: Prohibited HTTP method is used
      tags:
        - dentists
      description: List all dentists
      operationId: listDentists
  '/dentists/{id}':
    get:
      produces:
        - application/json
      parameters:
        - name: id
          description: A unique integer value identifying this dentist
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Successfully retrieved dentists
          schema:
            $ref: '#/definitions/Dentist'
        '400':
          description: Bad request (invalid dentist ID)
        '404':
          description: Dentist with the provided ID is not found
        '405':
          description: Prohibited HTTP method is used
      tags:
        - dentists
      description: Retrieve a dentist by ID
      operationId: retrieveDentist
definitions:
  Dentist:
    properties:
      id:
        readOnly: true
        type: integer
        example: 1
        description: ID of the dentist
      location:
        type: string
        example: Syndey
        description: Location of the dentist
      name:
        type: string
        example: Dr Green
        description: Name of the dentist
      specialization:
        type: string
        example: Orthodontics
        description: Specialization of the dentist
    required:
      - name
      - location
      - specialization
    type: object
x-components: {}

